
# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@8.1.2
jobs:
  make-doc:
    docker:
      - image: circleci/python:3.9-buster
    steps:
      - setup_remote_docker:
          version: 20.10.14    
      - run: sudo apt-get update
      - checkout
      - run: pip install --user sphinx_rtd_theme sphinx autodocsumm
      - run:
          name: Build doc
          command: |
            cd doc
            make html
#      - run: 
#          name: Build Docker Image
#          command: |
#            docker build -t shankarcit/app:latest doc

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  say-hello-workflow:
    jobs:
      - make-doc
  build_and_push_image:
    jobs:
      - aws-ecr/build-and-push-image:        
#          aws-access-key-id: $AWS_ACCESS_KEY_ID
          aws-cli-version: latest
#          aws-secret-access-key: $AWS_SECRET_ACCESS_KEY
          executor: aws-ecr/default
          new-profile-name: 
          create-repo: true
          extra-build-args: '--compress'
          region: ap-northeast-1
          path: doc
          platform: linux/amd64
          public-registry: false
          push-image: true
          repo: ecr-shankar-tool-box
          repo-scan-on-push: true
          skip-when-tags-exist: false
          tag: 'latest,myECRRepoTag'    
